#!/usr/bin/env python3
"""
Regenerate BACKLOG.md's §11 index from the on-disk FR markdown frontmatter.

Reads:   docs/feature-requests/*/FR-*.md  (excludes *.audit.md)
         docs/feature-requests/*/FR-*.audit.md  (for score lookup)
Updates: docs/feature-requests/BACKLOG.md  (only the §11 section + audit-count fields)

This tool prevents the BACKLOG status table from drifting against the FR-folder
reality. Run it after authoring a new FR or moving status. The §2-§8 per-phase
tables (status columns) are NOT auto-regenerated by this script — those still
require manual edits since they encode phase-grouping decisions. §11 is the
fully-derived view.

Run:    python3 tools/regen-backlog.py
        python3 tools/regen-backlog.py --check     # exit 1 if §11 would change
        python3 tools/regen-backlog.py --verbose

References:
- feature-request-audit skill §5 (How FRs surface back to BACKLOG.md)
- AGENTS.md §18 (Landing-page-specific FR conventions)
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FR_DIR = ROOT / "docs" / "feature-requests"
BACKLOG = FR_DIR / "BACKLOG.md"

# Section markers — between these two lines the script rewrites §11
S11_START = "## §11 — FRs authored to 10/10"
S12_START = "## §12 — Open backlog management"


# -- minimal YAML frontmatter parser ----------------------------------------
# We don't want a PyYAML dependency (the agent toolchain might not have it).
# This handles flat scalar fields, single-quoted strings, lists on one line,
# and ignores nested blocks (which we don't need to parse).
def parse_frontmatter(path: Path) -> dict:
    """Return frontmatter dict for an FR markdown, or {} if not parseable."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---", text, flags=re.DOTALL)
    if not m:
        return {}
    block = m.group(1)
    out: dict = {}
    for line in block.splitlines():
        # strip comments
        line = re.sub(r"\s+#\s.*$", "", line)
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        m2 = re.match(r"^([a-zA-Z_][\w]*)\s*:\s*(.*)$", line)
        if not m2:
            continue
        key, raw = m2.group(1), m2.group(2)
        out[key] = _coerce(raw)
    return out


def _coerce(raw: str):
    raw = raw.strip()
    if raw == "":
        return None
    if raw == "null" or raw == "~":
        return None
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [x.strip().strip('"').strip("'") for x in inner.split(",")]
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1]
    if raw.startswith("'") and raw.endswith("'"):
        return raw[1:-1]
    if raw.isdigit():
        return int(raw)
    return raw


# -- FR inventory ------------------------------------------------------------
def inventory() -> tuple[list[dict], dict[str, list[dict]]]:
    """Return (anchors, by_phase_extras).

    - anchors: one FR per module (the lowest-ordinal-bearing 10/10 from `engineering_anchor` frontmatter
      flag, else lowest-id 10/10) — preserved across phases.
    - by_phase_extras: dict[phase → list of 10/10 FRs not already an anchor], so nothing is dropped.
    """
    all_frs: list[dict] = []
    for fr in sorted(FR_DIR.glob("*/FR-*.md")):
        if fr.name.endswith(".audit.md"):
            continue
        fm = parse_frontmatter(fr)
        if not fm.get("id"):
            print(f"  warn: no id in {fr.relative_to(ROOT)}", file=sys.stderr)
            continue
        audit_path = fr.with_suffix(".audit.md").with_name(
            fr.name.replace(".md", ".audit.md")
        )
        score = _audit_score(audit_path)
        all_frs.append({
            "id": fm["id"],
            "module": fm.get("module", "?"),
            "title": fm.get("title", "(no title)"),
            "phase": fm.get("phase", "?"),
            "status": fm.get("status", "draft"),
            "engineering_anchor": fm.get("engineering_anchor", False) in (True, "true", "True"),
            "fr_path": fr.relative_to(FR_DIR).as_posix(),
            "audit_path": audit_path.relative_to(FR_DIR).as_posix() if audit_path.exists() else None,
            "audit_score": score,
        })

    by_module: dict[str, list[dict]] = defaultdict(list)
    for fr in all_frs:
        by_module[fr["module"]].append(fr)

    module_order = ["CHAR", "DS", "SCENE", "WEB", "PERF", "A11Y", "SEO", "CTA", "CMS", "OPS"]
    anchors: list[dict] = []
    for mod in module_order:
        ten_ten = [f for f in by_module.get(mod, []) if f["audit_score"] == "10/10"]
        if not ten_ten:
            continue
        # Prefer explicitly-flagged engineering_anchor; else lowest id
        flagged = [f for f in ten_ten if f["engineering_anchor"]]
        chosen = sorted(flagged or ten_ten, key=lambda f: f["id"])[0]
        anchors.append(chosen)

    # All other 10/10 FRs, grouped by phase (so nothing falls through the cracks).
    anchor_ids = {a["id"] for a in anchors}
    by_phase: dict[str, list[dict]] = defaultdict(list)
    for f in all_frs:
        if f["audit_score"] != "10/10":
            continue
        if f["id"] in anchor_ids:
            continue
        by_phase[f["phase"]].append(f)
    for phase in by_phase:
        by_phase[phase].sort(key=lambda f: f["id"])

    return anchors, by_phase


def _audit_score(audit_path: Path) -> str | None:
    if not audit_path.exists():
        return None
    text = audit_path.read_text(encoding="utf-8")
    for key in ("score_post_revision_3", "score_post_revision_2", "score_post_revision_1", "score_pre_revision"):
        m = re.search(rf"^{key}:\s*([0-9.]+/[0-9.]+)", text, flags=re.MULTILINE)
        if m:
            return m.group(1)
    return None


# -- §11 rendering -----------------------------------------------------------
PHASE_TITLES = {
    "P0": "P0 — Discovery, Narrative, Character",
    "P1": "P1 — DS Extension + Storyboards + Greybox",
    "P2": "P2 — Lumi Modeling, Rigging, Animation",
    "P3": "P3 — Web Foundation + Scene 0 Polished",
    "P4": "P4 — Scenes 1-6 Build-out + Choreography",
    "P5": "P5 — Performance / A11y / QA / Localization",
    "P6": "P6 — Soft Launch + Iteration",
}
PHASE_ORDER = ["P0", "P1", "P2", "P3", "P4", "P5", "P6"]


def render_section_11(anchors: list[dict], by_phase_extras: dict[str, list[dict]]) -> str:
    extras_total = sum(len(v) for v in by_phase_extras.values())
    total = len(anchors) + extras_total
    lines = [
        S11_START + f" (regenerated from FR folder; {total} FRs at 10/10)",
        "",
        f"{total} FRs fully written + audited. §11.1 lists one format anchor per module; "
        f"§11.2+ groups every other audited FR by phase so nothing falls through the cracks.",
        "",
        f"> **Note.** This section is regenerated by `tools/regen-backlog.py`. "
        f"Do NOT hand-edit. To update: change the FR / audit frontmatter and re-run.",
        "",
        f"### §11.1 — Per-module format anchors ({len(anchors)} FRs)",
        "",
        "| FR-ID | Module | Title | Phase | Audit score |",
        "|---|---|---|:-:|:-:|",
    ]
    for a in anchors:
        lines.append(_row(a))

    # Phase-grouped extras
    sub_idx = 2
    for phase in PHASE_ORDER:
        extras = by_phase_extras.get(phase, [])
        if not extras:
            continue
        lines.extend([
            "",
            f"### §11.{sub_idx} — {PHASE_TITLES[phase]} ({len(extras)} additional FRs)",
            "",
            "| FR-ID | Module | Title | Audit score |",
            "|---|---|---|:-:|",
        ])
        for f in extras:
            lines.append(_phase_row(f))
        sub_idx += 1

    # Closing note: which phases are now fully audited?
    p0_closed_msg = ""
    if by_phase_extras.get("P0") or any(a["phase"] == "P0" for a in anchors):
        p0_closed_msg = (
            "\n**P0 is fully audited.** All P0 FRs are at `status: accepted` with 10/10 audit scores. "
            "The phase gate (founder signoff on script + character sheet + mood board) is satisfied.\n"
        )
    lines.append(p0_closed_msg)

    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def _phase_row(fr: dict) -> str:
    title = fr["title"]
    if title.startswith('"') and title.endswith('"'):
        title = title[1:-1]
    score_text = f"[{fr['audit_score']}]({fr['audit_path']})" if fr["audit_path"] else fr["audit_score"]
    return (f"| [{fr['id']}]({fr['fr_path']}) | {fr['module']} | "
            f"{_truncate(title, 80)} | {score_text} |")


def _row(fr: dict) -> str:
    title = fr["title"]
    if title.startswith('"') and title.endswith('"'):
        title = title[1:-1]
    score_text = f"[{fr['audit_score']}]({fr['audit_path']})" if fr["audit_path"] else fr["audit_score"]
    return (f"| [{fr['id']}]({fr['fr_path']}) | {fr['module']} | "
            f"{_truncate(title, 70)} | {fr['phase']} | {score_text} |")


def _truncate(s: str, n: int) -> str:
    return s if len(s) <= n else s[: n - 1] + "…"


# -- BACKLOG.md surgery ------------------------------------------------------
def regenerate(check_only: bool, verbose: bool) -> int:
    if not BACKLOG.exists():
        print(f"error: {BACKLOG} not found", file=sys.stderr)
        return 2

    anchors, by_phase_extras = inventory()
    new_section = render_section_11(anchors, by_phase_extras)

    current = BACKLOG.read_text(encoding="utf-8")

    s11_idx = current.find(S11_START)
    s12_idx = current.find(S12_START)
    if s11_idx < 0 or s12_idx < 0:
        print(f"error: could not find §11/§12 markers in BACKLOG.md", file=sys.stderr)
        return 2
    if s12_idx < s11_idx:
        print(f"error: §12 appears before §11 in BACKLOG.md", file=sys.stderr)
        return 2

    updated = current[:s11_idx] + new_section + current[s12_idx:]

    if updated == current:
        if verbose:
            print("OK — §11 already in sync; no changes")
        return 0

    if check_only:
        print("§11 would change. Run without --check to write.", file=sys.stderr)
        if verbose:
            _diff_print(current[s11_idx:s12_idx], new_section)
        return 1

    BACKLOG.write_text(updated, encoding="utf-8")
    extras_total = sum(len(v) for v in by_phase_extras.values())
    phases = ", ".join(sorted(by_phase_extras.keys()))
    print(f"OK — wrote {len(anchors)} anchor + {extras_total} phase-grouped rows "
          f"({phases or 'no extras'}) to §11")
    return 0


def _diff_print(old: str, new: str) -> None:
    import difflib
    for line in difflib.unified_diff(old.splitlines(), new.splitlines(),
                                     fromfile="BACKLOG.md (current)",
                                     tofile="BACKLOG.md (regenerated)", lineterm=""):
        print(line)


# -- entry point -------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate BACKLOG.md §11 from FR folder.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if §11 would change; don't write")
    ap.add_argument("--verbose", action="store_true",
                    help="print debug + diff on --check failure")
    args = ap.parse_args()
    return regenerate(check_only=args.check, verbose=args.verbose)


if __name__ == "__main__":
    sys.exit(main())
