import { ImageResponse } from "next/og";
import { isLocale } from "@/lib/i18n/config";
import { company } from "@/lib/content/site";

export const alt = "CyberSkill - Turn Your Will Into Real";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// Per-locale social card. Generated by Next from this file; the og:image meta is
// wired automatically. No external fonts (system stack) so it builds offline.
export default async function OpengraphImage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  const locale = isLocale(lang) ? lang : "en";
  const tagline =
    locale === "vi" ? "Web - Di dong - He thong noi bo - TP Ho Chi Minh" : "Web - Mobile - Internal systems - Ho Chi Minh City";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "80px",
          background: "#45210E",
          color: "#FDF4E1",
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", fontSize: 34, color: "#F4BA17", letterSpacing: 6 }}>CYBERSKILL</div>
        <div style={{ display: "flex", fontSize: 86, fontWeight: 700, marginTop: 28, lineHeight: 1.05 }}>
          {company.slogan[locale]}
        </div>
        <div style={{ display: "flex", fontSize: 30, marginTop: 36, color: "#E7D9C4" }}>{tagline}</div>
      </div>
    ),
    { ...size },
  );
}
