import { ImageResponse } from "next/og";
import { isLocale } from "@/lib/i18n/config";
import { company } from "@/lib/content/site";

export const alt = "CyberSkill - Turn Your Will Into Real";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// Per-locale social card (LinkedIn, Zalo, X, email previews). Generated by Next
// from this file; the og:image meta is wired automatically. No external fonts
// (system stack) so it builds offline. Art direction mirrors the site: gold Lumi
// aura + orb on umber, the slogan, and a legitimacy line (domain + city).
export default async function OpengraphImage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  const locale = isLocale(lang) ? lang : "en";
  const tagline =
    locale === "vi" ? "Web - Di động - Hệ thống nội bộ" : "Web - Mobile - Internal systems";
  const place = locale === "vi" ? "TP Hồ Chí Minh" : "Ho Chi Minh City";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          position: "relative",
          overflow: "hidden",
          background: "#45210E",
          color: "#FDF4E1",
          fontFamily: "sans-serif",
        }}
      >
        {/* Soft aura behind Lumi (top-right). */}
        <div
          style={{
            position: "absolute",
            right: -180,
            top: -160,
            width: 860,
            height: 860,
            borderRadius: "50%",
            background:
              "radial-gradient(closest-side, rgba(244,186,23,0.50), rgba(244,186,23,0.10) 55%, rgba(244,186,23,0) 72%)",
          }}
        />
        {/* The Lumi orb - the mark, echoed from the favicon. */}
        <div
          style={{
            position: "absolute",
            right: 148,
            top: 172,
            width: 286,
            height: 286,
            borderRadius: "50%",
            background: "radial-gradient(circle at 42% 36%, #FCE9A8, #F4BA17 52%, #B5780A 100%)",
            boxShadow: "0 30px 90px rgba(244,186,23,0.35)",
            display: "flex",
          }}
        />
        {/* Content column. */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            padding: "84px",
            maxWidth: 780,
            position: "relative",
          }}
        >
          <div style={{ display: "flex", alignItems: "center" }}>
            <div
              style={{
                width: 14,
                height: 14,
                borderRadius: "50%",
                background: "#F4BA17",
                marginRight: 16,
                display: "flex",
              }}
            />
            <div style={{ display: "flex", fontSize: 30, color: "#F4BA17", letterSpacing: 8 }}>
              CYBERSKILL
            </div>
          </div>
          <div
            style={{ display: "flex", fontSize: 88, fontWeight: 700, marginTop: 26, lineHeight: 1.04 }}
          >
            {company.slogan[locale]}
          </div>
          <div style={{ display: "flex", fontSize: 30, marginTop: 32, color: "#E7D9C4" }}>{tagline}</div>
          <div style={{ display: "flex", alignItems: "center", marginTop: 52 }}>
            <div
              style={{ width: 60, height: 2, background: "#F4BA17", marginRight: 20, display: "flex" }}
            />
            <div style={{ display: "flex", fontSize: 26, color: "#C9B79B", letterSpacing: 2 }}>
              cyberskill.world  -  {place}
            </div>
          </div>
        </div>
      </div>
    ),
    { ...size },
  );
}
