import {
  defineField,
  defineType,
  EDITOR_GROUPS,
  imageWithAlt,
  localeField,
  newestOrdering,
  publishedAtField,
} from './shared';

export const job = defineType({
  name: 'job',
  type: 'document',
  title: 'Job',
  groups: EDITOR_GROUPS,
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      title: 'Title',
      group: 'content',
      validation: (Rule) => Rule.required().min(4).max(120),
    }),
    defineField({
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      group: 'metadata',
      options: { source: 'title', maxLength: 80 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'department',
      type: 'string',
      title: 'Department',
      group: 'metadata',
      options: { list: ['engineering', 'design', 'ops', 'growth'] },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'level',
      type: 'string',
      title: 'Level',
      group: 'metadata',
      options: { list: ['junior', 'mid', 'senior', 'principal'] },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'location_type',
      type: 'string',
      title: 'Location type',
      group: 'metadata',
      options: { list: ['remote', 'hybrid', 'hcmc-on-site'] },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'summary',
      type: 'blockContent',
      title: 'Summary',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      type: 'blockContent',
      title: 'Description',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'ats_external_id',
      type: 'string',
      title: 'ATS external ID',
      group: 'metadata',
    }),
    imageWithAlt({ name: 'social_image', title: 'Social image', group: 'seo' }),
    publishedAtField,
    defineField({
      name: 'closed_at',
      type: 'datetime',
      title: 'Closed at',
      group: 'workflow',
    }),
    localeField(),
  ],
  orderings: [newestOrdering],
});
